# Generated by Django 4.2.7 on 2023-12-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Format: YYYY-MM-DD HH:MM:SS', null=True),
        ),
    ]
